# Generated by Django 3.0.7 on 2024-02-19 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_auto_20240213_2248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(db_column='password', max_length=255, unique=True),
        ),
    ]
