# Generated by Django 3.0.7 on 2024-03-11 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20240218_2100'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True, verbose_name='last login'),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='password',
            field=models.CharField(db_column='password', max_length=255),
        ),
    ]
