# Generated by Django 3.0.7 on 2024-03-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_auto_20240310_1750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='userid',
        ),
        migrations.AddField(
            model_name='studentmodel',
            name='id',
            field=models.AutoField(db_column='id', default=1, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='studentmodel',
            name='email',
            field=models.EmailField(db_column='email', max_length=45, unique=True),
        ),
    ]
