# Generated by Django 3.0.7 on 2024-03-27 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_auto_20240311_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentmodel',
            name='id',
            field=models.AutoField(db_column='id', primary_key=True, serialize=False),
        ),
    ]
