# Generated by Django 3.0.7 on 2024-03-10 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('area', models.CharField(max_length=255)),
                ('bed', models.PositiveIntegerField()),
                ('bathroom', models.PositiveIntegerField()),
                ('student_comments', models.TextField()),
                ('stars', models.PositiveIntegerField()),
                ('image_url', models.URLField()),
                ('amenities', models.TextField()),
            ],
            options={
                'db_table': 'apartments',
                'managed': True,
            },
        ),
    ]
